"""add title and author to reviews

Revision ID: d0d524dab750
Revises: 08c2ef1bf45b
Create Date: 2026-06-26 16:00:45.861587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d524dab750'
down_revision: Union[str, None] = '08c2ef1bf45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('title', sa.String(), nullable=False))
    op.add_column('reviews', sa.Column('author', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'author')
    op.drop_column('reviews', 'title')
    # ### end Alembic commands ###
